version: "3.8"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    container_name: nginx_rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_server

  auth_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_server
    environment:
      - GIN_MODE=release
    ports:
      - "8081:8081"
